/* daily.js — day-rotating content for the hub "今日の習慣" band.
   Picked deterministically by day-of-year on the client (no backend).
   Edit freely; lists can be any length. */
window.DAILY = {
  quotes: [
    { ja: "私たちは繰り返し行うことの結果である。卓越とは行為ではなく、習慣である。", en: "We are what we repeatedly do. Excellence, then, is not an act but a habit.", src: "アリストテレス" },
    { ja: "習慣は第二の天性なり。", en: "Habit is second nature.", src: "ことわざ" },
    { ja: "小さな改善の積み重ねが、やがて大きな差になる。", en: "Small improvements, repeated, compound into remarkable results.", src: "習慣の科学より" },
    { ja: "やる気を待たない。仕組みが人を動かす。", en: "Don't wait for motivation — systems move us.", src: "行動デザインより" },
    { ja: "変わりたいなら、まず小さく始めよ。", en: "If you want to change, start absurdly small.", src: "小さな習慣より" },
    { ja: "目標を立てる人は多い。仕組みを作る人が続ける。", en: "Many set goals; those who build systems keep going.", src: "習慣の科学より" },
    { ja: "意志の力は有限。環境を整える方が続く。", en: "Willpower runs out; a good environment lasts.", src: "行動デザインより" },
    { ja: "完璧な一日より、続く一週間。", en: "A sustained week beats one perfect day.", src: "習慣化デザインラボ" },
    { ja: "昨日できなくても、今日また始めればいい。", en: "Missed yesterday? Just begin again today.", src: "習慣化デザインラボ" },
    { ja: "なりたい自分に、行動で一票を入れる。", en: "Each action is a vote for the person you want to become.", src: "アイデンティティ習慣より" },
    { ja: "千里の道も一歩から。", en: "A journey of a thousand miles begins with a single step.", src: "老子" },
    { ja: "塵も積もれば山となる。", en: "Even dust, piled up, becomes a mountain.", src: "ことわざ" },
    { ja: "今日の小さな一歩が、一年後の自分をつくる。", en: "Today's small step shapes who you are a year from now.", src: "習慣化デザインラボ" },
    { ja: "続けることは、才能ではなく設計である。", en: "Consistency is not talent — it's design.", src: "習慣化デザインラボ" },
    { ja: "記録すれば、行動は変わりはじめる。", en: "What gets measured starts to change.", src: "セルフモニタリングより" },
    { ja: "頑張りすぎない。だから続く。", en: "Don't overdo it — that's how it lasts.", src: "習慣化は、がんばらない" },
    { ja: "きっかけを決めれば、行動は自動になる。", en: "Decide the cue, and the action runs itself.", src: "実行意図より" },
    { ja: "一人より、仲間と。続ける力は分かち合える。", en: "Together beats alone — consistency can be shared.", src: "ソーシャルサポートより" },
    { ja: "良い習慣は易しく、悪い習慣は難しく。", en: "Make good habits easy and bad habits hard.", src: "行動デザインより" },
    { ja: "毎日でなくていい。やめないことが大事。", en: "It needn't be daily — just don't quit.", src: "習慣化デザインラボ" },
    { ja: "未来は、今日の習慣の延長線上にある。", en: "Your future lies along the line of today's habits.", src: "習慣化デザインラボ" },
    { ja: "始めるのに、完璧な準備はいらない。", en: "You don't need perfect conditions to begin.", src: "習慣化デザインラボ" },
  ],
  plus10: [
    { ja: "ひと駅手前で降りて歩く", en: "Get off one stop early and walk" },
    { ja: "水をコップ1杯、多めに飲む", en: "Drink one extra glass of water" },
    { ja: "エスカレーターより階段を使う", en: "Take the stairs instead of the escalator" },
    { ja: "寝る30分前にスマホを置く", en: "Put your phone down 30 min before bed" },
    { ja: "本を10分だけ読む", en: "Read for just 10 minutes" },
    { ja: "スクワットを5回する", en: "Do 5 squats" },
    { ja: "朝、カーテンを開けて光を浴びる", en: "Open the curtains and get morning light" },
    { ja: "今日よかったことを1つ書く", en: "Write down one good thing about today" },
    { ja: "机を1分だけ片づける", en: "Tidy your desk for one minute" },
    { ja: "1分間ストレッチする", en: "Stretch for one minute" },
    { ja: "野菜をもうひと口足す", en: "Add one more bite of vegetables" },
    { ja: "今日の予定を3行で書き出す", en: "Jot down today's plan in 3 lines" },
    { ja: "5回、深呼吸する", en: "Take 5 deep breaths" },
    { ja: "歩数をプラス10分ぶん増やす", en: "Add 10 minutes of walking" },
    { ja: "間食を1つ、果物に替える", en: "Swap one snack for fruit" },
    { ja: "学んだことを一言メモする", en: "Note one thing you learned, in a line" },
    { ja: "寝る時間を10分だけ早める", en: "Go to bed 10 minutes earlier" },
    { ja: "「ありがとう」を1回多く言う", en: "Say “thank you” one more time" },
    { ja: "通知を1つオフにする", en: "Turn off one notification" },
    { ja: "明日の服を前夜に決めておく", en: "Lay out tomorrow's clothes tonight" },
    { ja: "画面を見ない休憩を1回とる", en: "Take one screen-free break" },
    { ja: "今日続けたことに、自分でひと褒め", en: "Give yourself credit for one thing you kept up" },
  ],
};
