/* Habit Design Lab (太田賢研究室) — bilingual content.
   Built from the lab's real site + intro slides. A few private details are placeholders.
   Attaches window.LAB_DATA = { ja:{...}, en:{...} } */

window.LAB_DATA = {
  ja: {
    langLabel: "EN",
    brand: {
      lab: "太田賢研究室",
      labEn: "Ohta Lab",
      sub: "習慣化デザインラボ",
      uni: "宮城大学 事業構想学群 価値創造デザイン学類",
    },
    nav: [
      { id: "about", label: "研究室について" },
      { id: "research", label: "研究" },
      { id: "works", label: "学生の研究" },
      { id: "members", label: "メンバー" },
      { id: "publications", label: "業績" },
      { id: "news", label: "ニュース" },
      { id: "teaching", label: "教育" },
      { id: "join", label: "配属希望の方へ" },
    ],
    cta: "配属希望の方へ",
    hero: {
      eyebrow: "DESIGNING HABITS WITH AI & DESIGN",
      lines: [{ accent: false, units: ["「続かない」を"] }, { accent: true, units: ["「続けたくなる」へ。"] }],
      statement: "人の行動の、\n約43%は習慣でできている。",
      lead: "AI とデザインで、人の習慣を変える研究室。現実と仮想が融合する環境で、人が思わず“続けたくなる”仕掛けを設計します。",
      tagline: "デジタルとデータ、デザインで人を動かす。",
      stats: [
        { n: "43", unit: "%", label: "行動は習慣でできている" },
        { n: "22", unit: "名", label: "2023–2025 配属生" },
        { n: "3", unit: "レベル", label: "個人・組織・地域" },
      ],
      scroll: "研究室を見る",
    },
    about: {
      num: "01",
      kicker: "About",
      title: "「続かない」を、科学する。",
      lead: "YouTube をつい見すぎる。運動が続かない。勉強の習慣がつかない。早起きできない。\n人の習慣を変えるのは、案外むずかしい。\nでも、面白い。",
      aspire: "小さな習慣から、未来を変える。",
      visionLabel: "Vision",
      vision: "デジタルとデータ、デザインで人を動かす。",
      visionBody: "現実と仮想が融合する環境（サイバーフィジカルシステム）で、AI・IoT とデータ分析を使い、人が思わず“続けたくなる”仕掛けを設計する「ICT 行動変容支援技術」を探求します。小さく見える「続かない」も、健康寿命・医療費・働き方・学び・ウェルビーイングといった社会課題に直結します。",
      approachLabel: "Approach",
      approachTitle: "AI が答えを出す時代に、人は何をすべきか。",
      approachBody: "分析や予測は AI に任せられる。だからこそ人は、「何を続けるか」「どう生きたいか」という問いに向き合える。",
      sides: [
        { tag: "HUMAN", title: "意味・価値・共感", items: ["「どうありたいか」を問う", "動機づけ・感情的支援", "コーチング"] },
        { tag: "AI", title: "分析・予測・最適化", items: ["行動データの収集・分析", "習慣モデルで診断", "一人ひとりに最適化"] },
      ],
    },
    research: {
      num: "02",
      kicker: "Research",
      title: "研究テーマ",
      lead: "意志や根性に頼らず、「デジタルとデータ、デザイン」の力で人を動かす。個人・組織・地域の3つのレベルで研究と社会実装に取り組みます。",
      levels: [
        { tag: "個人", title: "Personal", body: "運動・学習・生活習慣の継続を支えるアプリ・AI コーチ。" },
        { tag: "組織", title: "Organization", body: "自治体・企業の健康増進事業や教育プログラムの支援システム。" },
        { tag: "地域", title: "Community", body: "コミュニティのデジタル変革と、住民の行動変容。" },
      ],
      themesLabel: "取り組む研究テーマ",
      themes: [
        "行動習慣に関する事例・知見の収集・解析と知識ベースの構築",
        "IoT センサーや対話を活用し、人の行動や状況を把握する行動センシング",
        "ゲーミフィケーション・AI コーチ・人的支援の協働による継続促進デザイン",
        "地域の課題解決・行動変容を促す ICT サービスデザインと社会実装",
      ],
      loopLabel: "サイバーフィジカルな習慣ループ",
      loop: [
        { side: "フィジカル", step: "行動の観察・センシング", body: "IoT・対話で行動や状況を把握" },
        { side: "サイバー", step: "分析・診断・AI コーチング", body: "ビッグデータと習慣モデルで診断" },
        { side: "サイバー", step: "パーソナライズ介入", body: "人間支援者との協調で働きかけ" },
        { side: "フィジカル", step: "学習し最適化", body: "反応や進捗を学び、システムを更新" },
      ],
      domainsLabel: "対象とする習慣の領域",
      domains: ["運動・スポーツ", "ヘルスケア", "学習", "スマホ利用", "食生活", "働き方・生産性", "環境・省エネ", "地域・コミュニティ"],
      projectsLabel: "主なプロジェクト",
      projects: [
        { tag: "地域 / 健康", title: "PROJECT HIKARI", sub: "地域の習慣化事業支援システム", body: "全国の運動・健康増進事業 263 件を収集し、PRECEDE-PROCEED モデルに基づき LLM で自動整理。対話型 RAG チャットボットで効果的な事業計画を支援します。" },
        { tag: "学習 / 教育", title: "PROJECT STELLA", sub: "教育支援AIチャットボット", body: "一人ひとりの学習スタイルや進捗に合わせて、教育を個別最適化。「学習型」「支援型」「メンタリング型」ボットが連携して学びの習慣をサポートします。" },
      ],
    },
    works: {
      num: "03",
      kicker: "Student Works",
      title: "あなたが創りあげたい​ものはなんですか？",
      lead: "",
      groups: [
        { tag: "行動習慣", items: ["自己分身アバターで目標行動を継続支援", "高齢者のスマホ利用 学習支援"] },
        { tag: "地域・コミュニケーション", items: ["町内会活動を促す地域コミュニケーション", "LINE グループ向け 情報整理アシスタント"] },
        { tag: "デジタルウェルビーイング", items: ["パターンランゲージで作る DW ツール", "YouTube 視聴パターンの可視化"] },
        { tag: "学習・創作支援", items: ["初学者向け プログラミング学習ボット", "創作活動を支援するチャットボット"] },
      ],
      link: "HABITUS 2025 の動画・詳細を見る",
    },
    members: {
      num: "04",
      kicker: "Members",
      title: "メンバー",
      lead: "2023〜2025 年度で 22 名の学生（情報系・空間系）が配属されました。",
      pi: {
        name: "太田 賢",
        reading: "おおた けん / Ken Ohta",
        role: "教授・博士（工学） / 情報システムセンター長",
        body: "宮城大学 事業構想学群 価値創造デザイン学類。静岡県静岡市出身。前職は NTT ドコモで、モバイル・IoT・AI・ビッグデータの新サービス研究開発に従事。",
        tags: ["サイバーフィジカルシステム", "モバイルコンピューティング", "ICT 行動変容システム", "行動・習慣化デザイン"],
      },
      groups: [
        { label: "大学院生", people: [{ name: "舛井 道晴", role: "博士後期" }] },
        { label: "学部生", people: [
          { name: "○○ ○○", role: "B4" }, { name: "○○ ○○", role: "B4" },
          { name: "○○ ○○", role: "B4" }, { name: "○○ ○○", role: "B3" },
          { name: "○○ ○○", role: "B3" }, { name: "○○ ○○", role: "B3" },
        ] },
      ],
      note: "※ 学部生の氏名はプレースホルダです。実際の名簿に差し替えてください。",
      cohortsLabel: "集合写真",
      cohortSuffix: "年度 配属生",
    },
    publications: {
      num: "05",
      kicker: "Publications",
      title: "業績・受賞",
      lead: "論文・招待講演・受賞の抜粋。",
      moreLabel: "業績をすべて見る",
      pageLead: "論文・招待講演・受賞の一覧です。カテゴリで絞り込めます。",
      researchmapLabel: "researchmap で全業績を見る",
      researchmapUrl: "https://researchmap.jp/kenohta",
      filters: ["すべて", "論文", "受賞", "著書"],
      items: [
        { cat: "論文", year: "2026", venue: "情報処理学会論文誌 Vol.67", title: "大規模言語モデルを用いた健康習慣化事業の事例データ管理フレームワークの構築", authors: "太田 賢" },
        { cat: "論文", year: "2026", venue: "情報処理学会 第88回全国大会", title: "教育支援 AI チャットボットの実践事例ナレッジベースの構築", authors: "太田 賢" },
        { cat: "受賞", year: "2025", venue: "内閣官房主催 イチBizアワード2025", title: "協賛企業賞 2件（国際航業様・ゼンリン様）「Otoneマップ―音を集めて作る、新しい地図―」", authors: "太田研究室 B チーム（武部ゆう, 武山千夏, 大川朋華, 矢吹尭弘）", url: "https://g-idea.go.jp/2025/winner/" },
        { cat: "受賞", year: "2025", venue: "DICOMO2025 シンポジウム", title: "優秀論文賞「地域の運動・健康増進事例を活用した習慣化事業支援システム」", authors: "太田 賢", url: "https://cir.nii.ac.jp/crid/1050868981231363840" },
        { cat: "受賞", year: "2025", venue: "学都「仙台・宮城」サイエンス・デイ", title: "役に立つ地学賞2025（仙台・東北のお祭りをビッグデータでみよう！）", authors: "太田研究室" },
        { cat: "受賞", year: "2024", venue: "情報処理学会 DICOMO2024", title: "活動功労賞", authors: "太田 賢" },
        { cat: "受賞", year: "2024", venue: "アーバンデータチャレンジ2023", title: "学生奨励賞「読み聞かせナビ」", authors: "松野 聡美・栗原 桜子・山内 涼真 ほか", url: "https://www.myu.ac.jp/academics/news/folder002/2024/7788/" },
        { cat: "受賞", year: "2023", venue: "「生成AI×教育」妄想アイデアオーディション", title: "部門別優秀賞", authors: "菅野 真唯", url: "https://www.myu.ac.jp/academics/news/folder002/2023/7688/" },
        { cat: "論文", year: "2025", venue: "DICOMO2025（招待講演）", title: "人と AI の協働による行動変容支援 —運動・健康・学びを支える習慣化デザイン—", authors: "太田 賢" },
        { cat: "論文", year: "2025", venue: "DICOMO2025", title: "地域の健康と食習慣を支援するプラットフォームの構築", authors: "舛井 道晴", url: "https://cir.nii.ac.jp/crid/1050024556301231616" },
        { cat: "著書", year: "2024", venue: "未来へつなぐデジタルシリーズ", title: "コンピュータネットワーク概論 第2版", authors: "水野 忠則 (監修・著), 太田 賢, 中村 嘉隆, 稲村 浩, 田学 軍, 石原 進, 久保田 真一郎, 舟阪 淳一, 清原 良三, 岡崎 直宣, 油田 健太郎 (著)", url: "https://www.amazon.co.jp/dp/4320125762/" },
        { cat: "著書", year: "2016", venue: "未来へつなぐデジタルシリーズ 33", title: "モバイルネットワーク", authors: "水野 忠則 (監修), 内藤 彩乃 (監修・著), 北須賀 輝明, 鈴木 秀和, 稲村 浩, 太田 賢, 今井 哲朗, 奥村 幸彦, 鈴木 信雄, 吉廣 卓哉, 森野 博章, 神崎 映光, 江原 正規, 梶 克彦, 村尾 和哉 (著)", url: "https://www.amazon.co.jp/dp/4320123530/" },
        { cat: "著書", year: "2023", venue: "翻訳", title: "コンピュータネットワーク 第6版（A. S. タネンバウム ほか）", authors: "アンドリュー・S・タネンバウム, ニック・フィームスター, デビッド.J.ウェセラル (著) / 水野 忠則, 相田 仁, 東野 輝夫, 太田 賢, 西垣 正勝, 渡辺 尚 (翻訳)", url: "https://www.amazon.co.jp/コンピュータネットワーク第6版-アンドリュー・S・タネンバウム/dp/4296070428" },
      ],
    },
    news: {
      num: "06",
      kicker: "News",
      title: "ニュース",
      lead: "受賞・発表・地域連携などの最新情報。",
      moreLabel: "ニュース一覧へ",
      pageLead: "受賞・発表・地域連携などの最新情報。カテゴリで絞り込めます。",
      items: [
        { date: "2026.03.06", tags: ["研究"], body: "情報処理学会 第88回全国大会で「教育支援 AI チャットボットの実践事例ナレッジベースの構築」を発表しました。" },
        { date: "2026.02.20", tags: ["研究室"], body: "#HABITUS2025 宮城大学卒業研究制作展＠メディアテークにて習慣化デザイン研究を展示しました。" },
        { date: "2026.01.30", tags: ["研究室", "表彰"], body: "内閣官房主催 イチBizアワード2025 にて、太田研究室 B チームが協賛企業賞2件（国際航業様・ゼンリン様）を受賞しました。" },
        { date: "2026.01.15", tags: ["研究"], body: "情報処理学会論文誌に論文「大規模言語モデルを用いた健康習慣化事業の事例データ管理フレームワークの構築」が掲載されました。" },
        { date: "2025.12.26", tags: ["地域課題解決", "研究室"], body: "「回覧板で振り返る！2025年の泉パークタウン」コンテンツを泉パークタウン公式 LINE に配信いただきました。" },
        { date: "2025.11.11", tags: ["研究", "表彰"], body: "「地域の運動・健康増進事例を活用した習慣化事業支援システム」が DICOMO2025 優秀論文賞をいただきました。" },
        { date: "2025.10.18", tags: ["地域課題解決", "研究室"], body: "多世代交流拠点 寺岡 Knots のスマホ教室で、学生が開発した AI ボットでスマホの使い方サポートを紹介しました。" },
        { date: "2025.07.20", tags: ["地域課題解決", "教育"], body: "学都「仙台・宮城」サイエンス・デイに「仙台・東北のお祭りをビッグデータでみよう！」を出展し、役に立つ地学賞2025をいただきました。" },
      ],
    },
    teaching: {
      num: "07",
      kicker: "Education",
      title: "教育・担当科目",
      lead: "情報通信を軸に、AI・データ・サービスデザインを実践的に学べます。",
      coursesLabel: "担当科目",
      courses: ["データサイエンス", "情報システムデザイン", "知能メディアデザイン", "コンピュータアルゴリズム", "人工知能とデザイン"],
      careersLabel: "こんなキャリアを目指す人に",
      careers: [
        { code: "SE", title: "システムエンジニア", body: "つくる力をキャリアに" },
        { code: "PLAN", title: "サービス企画・プランナー", body: "価値を設計する" },
        { code: "UX", title: "UX デザイナー", body: "人の体験をデザイン" },
        { code: "AI", title: "AI エンジニア", body: "知能を使いこなす" },
      ],
      booksLabel: "著書・翻訳",
      books: ["コンピュータネットワーク概論 第2版（未来へつなぐデジタルシリーズ）", "コンピュータネットワーク 第6版（翻訳）"],
      recurrentLabel: "社会人向けリカレント教育（DDX）",
      recurrent: "社会人・地域人材向けの DX 人材育成プログラム「Downstream から学ぶ DX（DDX）」にも携わっています。111 科目に対応した対話型 RAG チャットボットや、オンデマンド講座を学ぶ習慣を支えるアプリづくりを通じて、学び続ける人を支援しています。",
      recurrentLink: "MYU DDX のサイトを見る",
      recurrentUrl: "https://myuddx.jp",
    },
    join: {
      num: "08",
      kicker: "Join us",
      title: "興味がある方、まずお話ししましょう。",
      lead: "「面白そう」と思った方、大歓迎です。ビジョンに共感した方、得意や“好き”を活かしたい方、進学を考えている方も。情報系・空間系どちらも歓迎します。",
      processLabel: "卒業研究の進め方",
      process: [
        { n: "01", title: "テーマ設定", body: "自分の「続かない」や興味から始める" },
        { n: "02", title: "価値提案", body: "アイデアを企画し、カタチにする" },
        { n: "03", title: "評価・発表", body: "実験で確かめ、コンテストや学会で発表" },
      ],
      processNote: "週1回の対面ミーティング（進捗報告・議論）で伴走します。はじめは誰もが初心者。",
      craftLabel: "大切にしていること",
      craft: "手を動かし、試行錯誤しながら価値を創る。アプリ・AI ボット・IoT 空間サービスなど、実際に“動くもの”を創ることを大切にしています。",
      equipLabel: "使える機材",
      equip: ["スマートホーム機器（Echo・Fire TV・スマート照明）", "3D プリンター", "360°カメラ", "ロボット（Temi）", "VR ゴーグル", "iPad", "AI 用 PC"],
      audiences: [
        { for: "学部生", body: "プログラミングや統計の経験は問いません。まずは見学・面談からどうぞ。" },
        { for: "大学院生", body: "大学院進学も歓迎します。他大学・社会人からの進学もご相談ください。" },
        { for: "企業の方", body: "行動変容・ヘルスケア・地域連携での共同研究・PoC を歓迎します。" },
      ],
      deadlineLabel: "申込〆切",
      deadline: "6/8（月）",
      action: "メールで問い合わせる",
      audienceLabel: "対象",
      detailAction: "配属案内を見る",
      ctaShort: "「面白そう」と思った方、大歓迎です。まず見学・面談からどうぞ。",
      why: "「続かない」を、科学する。",
      whyBody: "YouTube をつい見すぎる。運動が続かない。勉強の習慣がつかない。早起きできない。——人の習慣を変えるのは、案外むずかしい。でも、面白い。その「続かない」、一緒に研究しませんか。",
      message: "人の行動の、約43%は習慣でできている。自分の「続かない」が、誰かの解決になる。",
      studentsLabel: "学生の取り組み",
      studentsNote: "2023〜2025年度で22名が配属。情報系・空間系どちらも在籍。受賞も多数（アーバンデータチャレンジ2023 学生奨励賞、「生成AI×教育」妄想アイデアオーディション 部門別優秀賞、イチBizアワード2025 協賛企業賞 など）。",
      faqLabel: "よくある質問",
      faq: [
        { q: "プログラミングや統計の経験がなくても大丈夫ですか？", a: "問いません。「人の行動をより良く変えたい」という関心があれば歓迎します。はじめは誰もが初心者です。" },
        { q: "情報系でなくても配属できますか？", a: "情報系・空間系どちらも在籍しています。照明や音で“整う部屋”をつくるスマートホームのテーマもあります。" },
        { q: "大学院に進学したいのですが。", a: "歓迎します。他大学・社会人からの進学もご相談ください。" },
        { q: "まず何をすればいいですか？", a: "見学・面談からどうぞ。気になったら、まずはメールでお気軽にご連絡ください。" },
      ],
    },
    access: {
      num: "09",
      kicker: "Access",
      title: "アクセス・連絡先",
      lead: "見学・お問い合わせはお気軽にどうぞ。",
      addrLabel: "所在地",
      addr: "宮城県黒川郡大和町学苑 1-1\n宮城大学 大和キャンパス",
      mailLabel: "メール",
      mail: "otak@myu.ac.jp",
      phoneLabel: "電話",
      phone: "022-377-8347",
      siteLabel: "現行サイト",
      site: "ohtalab.notion.site",
      mapNote: "キャンパスマップ / 地図プレースホルダ",
      mapEmbed: "https://maps.google.com/maps?q=38.349116,140.841230&z=16&hl=ja&output=embed",
      mapUrl: "https://www.google.co.jp/maps/search/38.349116,+140.841230",
      mapOpen: "Google マップで開く",
    },
    footer: {
      copyright: "© 2026 太田賢研究室（Ohta Lab） / 宮城大学 事業構想学群",
      note: "",
    },
  },

  en: {
    langLabel: "日本語",
    brand: {
      lab: "Ohta Lab",
      labEn: "太田賢研究室",
      sub: "Habit Design Lab",
      uni: "Value Creation Design, Miyagi University",
    },
    nav: [
      { id: "about", label: "About" },
      { id: "research", label: "Research" },
      { id: "works", label: "Student Works" },
      { id: "members", label: "Members" },
      { id: "publications", label: "Publications" },
      { id: "news", label: "News" },
      { id: "teaching", label: "Education" },
      { id: "join", label: "Join" },
    ],
    cta: "Prospective students",
    hero: {
      eyebrow: "DESIGNING HABITS WITH AI & DESIGN",
      lines: [{ accent: false, units: ["Turning ", "“I can't ", "keep it up”"] }, { accent: true, units: ["into ", "“I want to ", "keep going.”"] }],
      statement: "About 43% of\nhuman behavior is habit.",
      lead: "A lab that changes human habits with AI and design — building cues that make people genuinely want to keep going, where the physical and digital worlds merge.",
      tagline: "Moving people with digital, data and design.",
      stats: [
        { n: "43", unit: "%", label: "of behavior is habit" },
        { n: "22", unit: "", label: "students, 2023–2025" },
        { n: "3", unit: "", label: "levels: self · org · region" },
      ],
      scroll: "Explore the lab",
    },
    about: {
      num: "01",
      kicker: "About",
      title: "Making a science of “I can't keep it up.”",
      lead: "Watching too much YouTube. Can't keep exercising. No study habit. Can't wake up early.\nChanging habits is surprisingly hard — and surprisingly fascinating.",
      aspire: "From small habits, we change the future.",
      visionLabel: "Vision",
      vision: "Moving people with digital, data and design.",
      visionBody: "In cyber-physical environments where the real and virtual merge, we use AI, IoT and data analysis to design ICT behavior-change support — cues that make people want to keep going. Small struggles to “keep it up” connect directly to bigger issues: healthy lifespan, medical cost, work, learning and well-being.",
      approachLabel: "Approach",
      approachTitle: "In an age when AI gives the answers, what should people do?",
      approachBody: "Analysis and prediction can be left to AI. That frees people to face the real questions — what to keep doing, how to live.",
      sides: [
        { tag: "HUMAN", title: "Meaning · value · empathy", items: ["Asking “how do I want to be?”", "Motivation & emotional support", "Coaching"] },
        { tag: "AI", title: "Analysis · prediction · optimization", items: ["Collecting & analyzing behavior data", "Diagnosing with habit models", "Personalizing for each person"] },
      ],
    },
    research: {
      num: "02",
      kicker: "Research",
      title: "Research themes",
      lead: "Not willpower, but the power of digital, data and design. We pursue research and real-world deployment at three levels — the individual, the organization, and the region.",
      levels: [
        { tag: "Self", title: "Personal", body: "Apps and AI coaches that sustain exercise, learning and lifestyle habits." },
        { tag: "Org", title: "Organization", body: "Support systems for health-promotion and education programs of cities and companies." },
        { tag: "Region", title: "Community", body: "Digital transformation of communities and behavior change among residents." },
      ],
      themesLabel: "Research themes",
      themes: [
        "Collecting and analyzing habit cases & knowledge, and building a knowledge base",
        "Behavior sensing with IoT sensors and dialogue to grasp people's actions and context",
        "Continuation-promoting design combining gamification, AI coaches and human support",
        "ICT service design for regional problem-solving and behavior change, with real deployment",
      ],
      loopLabel: "The cyber-physical habit loop",
      loop: [
        { side: "Physical", step: "Observe & sense", body: "Grasp behavior via IoT & dialogue" },
        { side: "Cyber", step: "Analyze & coach", body: "Diagnose with big data & habit models" },
        { side: "Cyber", step: "Personalized intervention", body: "Act in concert with human supporters" },
        { side: "Physical", step: "Learn & optimize", body: "Learn from responses; update the system" },
      ],
      domainsLabel: "Habit domains we work on",
      domains: ["Exercise & Sport", "Healthcare", "Learning", "Smartphone use", "Diet", "Work & Productivity", "Environment & Energy", "Community"],
      projectsLabel: "Selected projects",
      projects: [
        { tag: "Region / Health", title: "PROJECT HIKARI", sub: "Regional habit-program support system", body: "We collected 263 nationwide exercise/health programs and organize them with an LLM based on the PRECEDE-PROCEED model. A conversational RAG chatbot supports effective program planning." },
        { tag: "Learning / Edu", title: "PROJECT STELLA", sub: "Educational AI chatbots", body: "Personalizing learning to each student's style and progress. Learning-, support- and mentoring-type bots work together to sustain study habits." },
      ],
    },
    works: {
      num: "03",
      kicker: "Student Works",
      title: "What do you want to create?",
      lead: "",
      groups: [
        { tag: "Habits", items: ["Sustaining goal behavior with an avatar self", "Smartphone-use learning support for seniors"] },
        { tag: "Community", items: ["Boosting neighborhood-association activity", "Info-organizing assistant for LINE groups"] },
        { tag: "Digital Well-being", items: ["A DW tool built with pattern language", "Visualizing YouTube viewing patterns"] },
        { tag: "Learning & Creativity", items: ["A programming-learning bot for beginners", "A chatbot that supports creative work"] },
      ],
      link: "See HABITUS 2025 works & videos",
    },
    members: {
      num: "04",
      kicker: "Members",
      title: "Members",
      lead: "22 students (information & space-design backgrounds) joined between 2023–2025.",
      pi: {
        name: "Ken Ohta",
        reading: "太田 賢",
        role: "Professor, Ph.D. (Eng.) / Director, Information Systems Center",
        body: "Value Creation Design, School of Project Design, Miyagi University. From Shizuoka. Previously at NTT DOCOMO, researching new mobile, IoT, AI and big-data services.",
        tags: ["Cyber-physical systems", "Mobile computing", "ICT behavior change", "Habit design"],
      },
      groups: [
        { label: "Graduate", people: [{ name: "Michiharu Masui", role: "Ph.D." }] },
        { label: "Undergrad", people: [
          { name: "○○ ○○", role: "B4" }, { name: "○○ ○○", role: "B4" },
          { name: "○○ ○○", role: "B4" }, { name: "○○ ○○", role: "B3" },
          { name: "○○ ○○", role: "B3" }, { name: "○○ ○○", role: "B3" },
        ] },
      ],
      note: "* Undergraduate names are placeholders — replace with the real roster.",
      cohortsLabel: "Group photos",
      cohortSuffix: " cohort",
    },
    publications: {
      num: "05",
      kicker: "Publications",
      title: "Publications & Awards",
      lead: "Selected papers, invited talks and awards.",
      moreLabel: "See all publications",
      pageLead: "A list of papers, invited talks and awards. Filter by category.",
      researchmapLabel: "See the full list on researchmap",
      researchmapUrl: "https://researchmap.jp/kenohta",
      filters: ["All", "Paper", "Award", "Book"],
      items: [
        { cat: "Paper", year: "2026", venue: "IPSJ Journal Vol.67", title: "An LLM-based case-data management framework for health habit programs", authors: "K. Ohta" },
        { cat: "Paper", year: "2026", venue: "IPSJ 88th National Convention", title: "Building a case knowledge base for educational AI chatbots", authors: "K. Ohta" },
        { cat: "Award", year: "2025", venue: "Ichi-Biz Award 2025 (Cabinet Secretariat)", title: "Two partner-company awards (Kokusai Kogyo, Zenrin) — “Otone Map: A New Map Built from Sound”", authors: "Ohta Lab Team B (Y. Takebe, C. Takeyama, T. Okawa, T. Yabuki)", url: "https://g-idea.go.jp/2025/winner/" },
        { cat: "Award", year: "2025", venue: "DICOMO 2025", title: "Best Paper: A habit-program support system using regional exercise/health cases", authors: "K. Ohta", url: "https://cir.nii.ac.jp/crid/1050868981231363840" },
        { cat: "Award", year: "2025", venue: "Sendai-Miyagi Science Day", title: "2025 prize (‘See Tohoku's festivals through big data’)", authors: "Ohta Lab" },
        { cat: "Award", year: "2024", venue: "IPSJ DICOMO 2024", title: "Service Award", authors: "K. Ohta" },
        { cat: "Award", year: "2024", venue: "Urban Data Challenge 2023", title: "Student Award (‘Yomikikase Navi’)", authors: "Matsuno, Kurihara, Yamauchi et al.", url: "https://www.myu.ac.jp/academics/news/folder002/2024/7788/" },
        { cat: "Award", year: "2023", venue: "’Gen-AI × Education’ idea audition", title: "Category prize", authors: "M. Kanno", url: "https://www.myu.ac.jp/academics/news/folder002/2023/7688/" },
        { cat: "Paper", year: "2025", venue: "DICOMO 2025 (Invited)", title: "Human–AI collaboration for behavior change — habit design for exercise, health and learning", authors: "K. Ohta" },
        { cat: "Paper", year: "2025", venue: "DICOMO 2025", title: "Building a platform to support regional health and diet habits", authors: "M. Masui", url: "https://cir.nii.ac.jp/crid/1050024556301231616" },
        { cat: "Book", year: "2024", venue: "Digital Series", title: "Introduction to Computer Networks, 2nd ed.", authors: "T. Mizuno (ed. & author), K. Ohta, Y. Nakamura, H. Inamura, X. Tian, S. Ishihara, S. Kubota, J. Funasaka, R. Kiyohara, N. Okazaki, K. Aburida (authors)", url: "https://www.amazon.co.jp/dp/4320125762/" },
        { cat: "Book", year: "2016", venue: "Digital Series 33", title: "Mobile Networks", authors: "T. Mizuno (supervising ed.), A. Naito (supervising ed. & author), T. Kitasuka, H. Suzuki, H. Inamura, K. Ohta, T. Imai, Y. Okumura, N. Suzuki, T. Yoshihiro, H. Morino, H. Kanzaki, M. Ehara, K. Kaji, K. Murao (authors)", url: "https://www.amazon.co.jp/dp/4320123530/" },
        { cat: "Book", year: "2023", venue: "Translation", title: "Computer Networks, 6th ed. (Tanenbaum et al.)", authors: "A. S. Tanenbaum, N. Feamster, D. J. Wetherall (authors) / T. Mizuno, H. Aida, T. Higashino, K. Ohta, M. Nishigaki, T. Watanabe (trans.)", url: "https://www.amazon.co.jp/コンピュータネットワーク第6版-アンドリュー・S・タネンバウム/dp/4296070428" },
      ],
    },
    news: {
      num: "06",
      kicker: "News",
      title: "News",
      lead: "Latest awards, talks and community work.",
      moreLabel: "All news",
      pageLead: "Latest awards, talks and community work. Filter by category.",
      items: [
        { date: "2026.03.06", tags: ["Research"], body: "Presented “Building a case knowledge base for educational AI chatbots” at IPSJ's 88th National Convention." },
        { date: "2026.02.20", tags: ["Lab"], body: "Exhibited habit-design research at #HABITUS2025, the Miyagi University graduation exhibition @ Mediatheque." },
        { date: "2026.01.30", tags: ["Lab", "Award"], body: "Ohta Lab Team B won two partner-company awards (Kokusai Kogyo, Zenrin) at the Cabinet Secretariat's Ichi-Biz Award 2025." },
        { date: "2026.01.15", tags: ["Research"], body: "Our paper on an LLM-based case-data framework for health habit programs appeared in the IPSJ Journal." },
        { date: "2025.12.26", tags: ["Community", "Lab"], body: "Our “Looking back on 2025 Izumi Park Town” content was distributed via the official Izumi Park Town LINE." },
        { date: "2025.11.11", tags: ["Research", "Award"], body: "“A habit-program support system using regional exercise/health cases” received a DICOMO 2025 Best Paper award." },
        { date: "2025.10.18", tags: ["Community", "Lab"], body: "At Teraoka Knots' smartphone class, we introduced a student-built AI bot to help with phone use." },
        { date: "2025.07.20", tags: ["Community", "Education"], body: "Exhibited “See Tohoku's festivals through big data” at Sendai-Miyagi Science Day and received a 2025 prize." },
      ],
    },
    teaching: {
      num: "07",
      kicker: "Education",
      title: "Education & Courses",
      lead: "Learn AI, data and service design hands-on, grounded in information & communications.",
      coursesLabel: "Courses",
      courses: ["Data Science", "Information System Design", "Intelligent Media Design", "Computer Algorithms", "AI & Design"],
      careersLabel: "For those aiming for careers like these",
      careers: [
        { code: "SE", title: "Systems Engineer", body: "Turn building into a career" },
        { code: "PLAN", title: "Service Planner", body: "Design value" },
        { code: "UX", title: "UX Designer", body: "Design experiences" },
        { code: "AI", title: "AI Engineer", body: "Master intelligence" },
      ],
      booksLabel: "Books & Translations",
      books: ["Introduction to Computer Networks, 2nd ed.", "Computer Networks, 6th ed. (translation)"],
      recurrentLabel: "Recurrent education for working adults (DDX)",
      recurrent: "We also contribute to “Learning DX from Downstream” (DDX), a DX reskilling program for working adults and regional talent — building a conversational RAG chatbot covering 111 courses and an app that helps sustain on-demand study habits.",
      recurrentLink: "Visit the MYU DDX site",
      recurrentUrl: "https://myuddx.jp",
    },
    join: {
      num: "08",
      kicker: "Join us",
      title: "Curious? Let's talk first.",
      lead: "If it sounds interesting, you're very welcome — whether you share the vision, want to use your strengths, or are thinking about grad school. Both information and space backgrounds welcome.",
      processLabel: "How graduation research works",
      process: [
        { n: "01", title: "Set a theme", body: "Start from your own “can't keep it up” or interests" },
        { n: "02", title: "Propose value", body: "Plan an idea and give it form" },
        { n: "03", title: "Evaluate & present", body: "Verify by experiment; present at contests and conferences" },
      ],
      processNote: "We meet in person once a week to discuss progress. Everyone starts as a beginner.",
      craftLabel: "What we value",
      craft: "Making things with our hands, learning by trial and error. We value building things that actually run — apps, AI bots, IoT spatial services.",
      equipLabel: "Equipment you can use",
      equip: ["Smart-home gear (Echo · Fire TV · smart lighting)", "3D printer", "360° camera", "Robot (Temi)", "VR goggles", "iPad", "AI workstation"],
      audiences: [
        { for: "Undergrads", body: "No prior programming or statistics required. Come for a visit or a chat anytime." },
        { for: "Grad students", body: "Grad school is welcome — including from other universities and industry." },
        { for: "Industry", body: "We welcome joint research and PoCs in behavior change, healthcare and community work." },
      ],
      deadlineLabel: "Application deadline",
      deadline: "Mon, Jun 8",
      action: "Email us",
      audienceLabel: "Who we welcome",
      detailAction: "See the full guide",
      ctaShort: "If it sounds interesting, you're very welcome. Start with a visit or a chat.",
      why: "Making a science of “I can't keep it up.”",
      whyBody: "Watching too much YouTube. Can't keep exercising. No study habit. Can't wake up early. Changing habits is surprisingly hard — and surprisingly fascinating. Want to research that with us?",
      message: "About 43% of human behavior is habit. Your own “I can't keep it up” can become someone else's solution.",
      studentsLabel: "Student activity",
      studentsNote: "22 students joined between 2023–2025, from both information and space backgrounds, with many awards (Urban Data Challenge 2023 Student Award; a category prize at the “Gen-AI × Education” idea audition; partner-company awards at Ichi-Biz Award 2025).",
      faqLabel: "FAQ",
      faq: [
        { q: "Do I need programming or statistics experience?", a: "No. Curiosity about changing behavior for the better is enough. Everyone starts as a beginner." },
        { q: "Can I join even if I'm not in an information major?", a: "Both information- and space-design students are here — including smart-home themes that craft a calming room with light and sound." },
        { q: "I'd like to go to grad school.", a: "Welcome — including from other universities and industry. Let's talk individually." },
        { q: "What should I do first?", a: "Start with a visit or interview. If it sounds interesting, just drop us an email." },
      ],
    },
    access: {
      num: "09",
      kicker: "Access",
      title: "Access & Contact",
      lead: "Visits and inquiries are always welcome.",
      addrLabel: "Address",
      addr: "Miyagi University, Taiwa Campus\n1-1 Gakuen, Taiwa, Kurokawa, Miyagi, Japan",
      mailLabel: "Email",
      mail: "otak@myu.ac.jp",
      phoneLabel: "Phone",
      phone: "022-377-8347",
      siteLabel: "Current site",
      site: "ohtalab.notion.site",
      mapNote: "Campus map / map placeholder",
      mapEmbed: "https://maps.google.com/maps?q=38.349116,140.841230&z=16&hl=en&output=embed",
      mapUrl: "https://www.google.co.jp/maps/search/38.349116,+140.841230",
      mapOpen: "Open in Google Maps",
    },
    footer: {
      copyright: "© 2026 Ohta Lab / School of Project Design, Miyagi University",
      note: "",
    },
  },
};
